name       : python-pyside
version    : 1.2.4
release    : 5
source     :
    - https://pypi.python.org/packages/36/ac/ca31db6f2225844d37a41b10615c3d371587677efd074db29855e7035de6/PySide-1.2.4.tar.gz : 1421bc1bf612c396070de9e1ffe227c07c1f3129278bc7d30c754b5146be2433
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python bindings for the Qt application and UI framework
description: |
    Python bindings for the Qt application and UI framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(QtCore)
    - pkgconfig(shiboken)
    - pyicu
build      : |
    cd sources/pyside
    %cmake \
        -DBUILD_TESTS=OFF \
        -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake-qt4 \
        -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 .
    %make
install    : |
    cd sources/pyside
    %make_install
    cd $workdir
    install -dm00644 $installdir/usr/lib/python2.7/site-packages/
    cp -R pyside_package/PySide.egg-info $installdir/usr/lib/python2.7/site-packages/pyside-$version-py2.7.egg-info
